config/routes.rb
Rails.application.routes.draw do
  resources :articles 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all 
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
          redirect_to @article
        else
            render action: 'new'
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render action: 'edit'

        end
    end


    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to @article

    end

    private

    def article_params
        params.require(:article).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= form_with(model: @article, local: true, data: {turbo: false}, url: article_path(@article), method: :put) do |f|%>
    <%= f.label :title%><br/>
    <%= f.text_field :title%><br/>
    <%= f.label :body%><br/>
    <%= f.text_area :body%><br/>
    <%= f.submit 'Submit'%>
<% end %>

app/views/articles/index.html.erb
<h3>Articles: </h3>
<% @articles.each do |article|%>
    <p>
        <%= article.title%>
    </p>

    <p>
        <%= article.body%>
    </p>
    <%= link_to 'Show', article_path(article)%>|<%= link_to 'Edit', edit_article_path(article)%>
    <p><%= button_to 'Delete',  article_path(article), data: {turbo: false}, method: :delete%></p>
    <hr/>
<% end %>

app/views/articles/new.html.erb
<%= form_with(model: @article, local: true, data: {turbo: false}, url: articles_path) do |f|%>
    <%= f.label :title%><br/>
    <%= f.text_field :title%><br/>
    <%= f.label :body%><br/>
    <%= f.text_area :body%><br/>
    <%= f.submit 'Submit'%>
<% end %>

app/views/articles/show.html.erb
<h3>Article:</h3>

<p><%= @article.title%></p>
<p><%= @article.body%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>